- hosts: terraform-ansible
  tasks:
    - name: Criando o arquivo
      copy:
        dest: /home/ubuntu/index.html
        content: <h1>Eh verdade esse bilhete!</h1>
    - name: Criando o servidor
      shell: "nohup busybox httpd -f -p 8080 &"